### PR TITLE
Update OpenFGA Implementation Service Providers List with Mrikal

### PR DESCRIPTION
**Pull request by HarshVoidUpparwal**
## Description

The primary goal of this update is to provide organizations with a comprehensive list of companies that can assist with implementing OpenFGA. By including Mrikal, we aim to enhance the resources available to users and support the wider adoption of OpenFGA solutions.
## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`

### CODE REVIEW

**Comment by aaguiarz** [comment]
Hi @HarshVoidUpparwal 

Could you please fix the merge conflicts? 🙏 

Thanks a lot

**Comment by HarshVoidUpparwal** [comment]
@aaguiarz Hi, I have resolved the conflict. Please review the changes.

Thanks

**Comment by aaguiarz** [comment]
@HarshVoidUpparwal pease make sure you leave the other company in the list too :)

**Comment by HarshVoidUpparwal** [comment]
@aaguiarz Please review now and let me know if anything else is required

**Review by aaguiarz — APPROVED** [review]

**Comment by aaguiarz** [comment]
@HarshVoidUpparwal merged, thanks a lot!

**Pull request merged**
